Repository areweguiyet/areweguiyet, pull requests merged in 2023-09, with the labels that each got.

#123 Add Rust-In-Flutter
  ecosystem.toml
Labels: gui-crate-framework

#124 Various data cleanup
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/cli.rs
  content/newsfeed/links.toml
  ecosystem.toml
Labels: enhancement, gui-crate-framework

#127 Fix image tag
  templates/base.tera.html
Labels: bug

#125 Rewrite JS to be mostly handled by the templating system
  .gitignore
  cli/src/cli.rs
  static/main.css
  static/main.js
  static/tag_sorting.js
  templates/base.tera.html
  templates/index.tera.html
Labels: enhancement, cli
